/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PaymentGatewayRouteImport } from './routes/payment-gateway'
import { Route as PosSystemRouteImport } from './routes/pos-system'
import { Route as WebDevelopmentRouteImport } from './routes/web-development'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentGatewayRoute = PaymentGatewayRouteImport.update({
  id: '/payment-gateway',
  path: '/payment-gateway',
  getParentRoute: () => rootRouteImport,
} as any)
const PosSystemRoute = PosSystemRouteImport.update({
  id: '/pos-system',
  path: '/pos-system',
  getParentRoute: () => rootRouteImport,
} as any)
const WebDevelopmentRoute = WebDevelopmentRouteImport.update({
  id: '/web-development',
  path: '/web-development',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/payment-gateway': typeof PaymentGatewayRoute
  '/pos-system': typeof PosSystemRoute
  '/web-development': typeof WebDevelopmentRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/payment-gateway': typeof PaymentGatewayRoute
  '/pos-system': typeof PosSystemRoute
  '/web-development': typeof WebDevelopmentRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/payment-gateway': typeof PaymentGatewayRoute
  '/pos-system': typeof PosSystemRoute
  '/web-development': typeof WebDevelopmentRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/payment-gateway' | '/pos-system' | '/web-development'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/payment-gateway' | '/pos-system' | '/web-development'
  id: '__root__' | '/' | '/payment-gateway' | '/pos-system' | '/web-development'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PaymentGatewayRoute: typeof PaymentGatewayRoute
  PosSystemRoute: typeof PosSystemRoute
  WebDevelopmentRoute: typeof WebDevelopmentRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment-gateway': {
      id: '/payment-gateway'
      path: '/payment-gateway'
      fullPath: '/payment-gateway'
      preLoaderRoute: typeof PaymentGatewayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pos-system': {
      id: '/pos-system'
      path: '/pos-system'
      fullPath: '/pos-system'
      preLoaderRoute: typeof PosSystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/web-development': {
      id: '/web-development'
      path: '/web-development'
      fullPath: '/web-development'
      preLoaderRoute: typeof WebDevelopmentRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PaymentGatewayRoute: PaymentGatewayRoute,
  PosSystemRoute: PosSystemRoute,
  WebDevelopmentRoute: WebDevelopmentRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
